services:
    netgen_admin_ui.controller.base:
        class: Netgen\Bundle\AdminUIBundle\Controller\Controller
        abstract: true
        calls:
            - [initialize, ["@service_container"]]
