parameters:
    netgen_admin_ui.controller.base.class: Netgen\Bundle\AdminUIBundle\Controller\Controller

services:
    netgen_admin_ui.controller.base:
        class: "%netgen_admin_ui.controller.base.class%"
        abstract: true
        calls:
            - [initialize, ["@service_container"]]
