imports:
    - { resource: parameters.yml }

ezpublish:
    system:
        administration_group:
            user:
                layout: "NetgenAdminUIBundle::pagelayout_login.html.twig"
                login_template: "NetgenAdminUIBundle:user:login.html.twig"

ez_publish_legacy:
    system:
        administration_group:
            templating:
                view_layout: "NetgenAdminUIBundle::pagelayout_legacy.html.twig"
                module_layout: "NetgenAdminUIBundle::pagelayout_module.html.twig"
