parameters:
    netgen_admin_ui.default.is_admin_ui_siteaccess: false

    netgen_admin_ui.ngadminui.is_admin_ui_siteaccess: true
    eztags.ngadminui.routing.enable_tag_router: false
    ezsettings.ngadminui.treemenu.http_cache: false
