parameters:
    ngmore.administration_group.pagelayout: 'NetgenMoreAdminUIBundle::pagelayout.html.twig'
    ngmore.administration_group.content_view.show_invisible_locations: true
    eztags.administration_group.routing.enable_tag_router: false
    ezsettings.administration_group.treemenu.http_cache: false
