ngadminui_homepage:
    path: /

_ezpublishPreviewContentDefaultSa:
    path: /content/versionview/{contentId}/{versionNo}/{language}
    defaults:
        _controller: "ezpublish_legacy.controller:indexAction"
    methods:  [GET]
