parameters:
    netgen_admin_ui.event_listener.security.class: Netgen\Bundle\AdminUIBundle\EventListener\SecurityListener
    netgen_admin_ui.helper.path_helper.class: Netgen\Bundle\AdminUIBundle\Helper\PathHelper

services:
    netgen_admin_ui.event_listener.security:
        class: "%netgen_admin_ui.event_listener.security.class%"
        arguments:
            - "@request_stack"
            - "@ezpublish.api.repository"
            - "@ezpublish.config.resolver"
            - "@security.context"
        tags:
            - { name: kernel.event_subscriber }

    netgen_admin_ui.helper.path_helper:
        class: "%netgen_admin_ui.helper.path_helper.class%"
        arguments:
            - "@ezpublish.api.service.location"
            - "@ezpublish.translation_helper"
            - "@router"
        calls:
            - [setRootLocationId, ["$content.tree_root.location_id$"]]
