parameters:
    netgen_admin_ui.event_listener.security.class: Netgen\Bundle\AdminUIBundle\EventListener\SecurityListener
    netgen_admin_ui.event_listener.legacy_response.class: Netgen\Bundle\AdminUIBundle\EventListener\LegacyResponseListener
    netgen_admin_ui.event_listener.legacy_exception.class: Netgen\Bundle\AdminUIBundle\EventListener\LegacyExceptionListener
    netgen_admin_ui.event_listener.controller.class: Netgen\Bundle\AdminUIBundle\EventListener\ControllerListener
    netgen_admin_ui.helper.path_helper.class: Netgen\Bundle\AdminUIBundle\Helper\PathHelper

services:
    netgen_admin_ui.event_listener.security:
        class: "%netgen_admin_ui.event_listener.security.class%"
        arguments:
            - "@request_stack"
            - "@ezpublish.api.repository"
            - "@ezpublish.config.resolver"
            - "@security.context"
        tags:
            - { name: kernel.event_subscriber }

    netgen_admin_ui.event_listener.legacy_response:
        class: "%netgen_admin_ui.event_listener.legacy_response.class%"
        arguments:
            - "$legacy_mode$"
        tags:
            - { name: kernel.event_subscriber }

    netgen_admin_ui.event_listener.legacy_exception:
        class: "%netgen_admin_ui.event_listener.legacy_exception.class%"
        arguments:
            - "$is_admin_ui_siteaccess;netgen_admin_ui$"
        tags:
            - { name: kernel.event_subscriber }

    netgen_admin_ui.event_listener.controller:
        class: "%netgen_admin_ui.event_listener.controller.class%"
        arguments:
            - "@controller_resolver"
            - "$is_admin_ui_siteaccess;netgen_admin_ui$"
            - "$legacy_routes;netgen_admin_ui$"
        tags:
            - {name: kernel.event_subscriber}

    netgen_admin_ui.helper.path_helper:
        class: "%netgen_admin_ui.helper.path_helper.class%"
        arguments:
            - "@ezpublish.api.service.location"
            - "@ezpublish.translation_helper"
            - "@router"
        calls:
            - [setRootLocationId, ["$content.tree_root.location_id$"]]
