parameters:
    netgen_admin_ui.event_listener.security.class: Netgen\Bundle\AdminUIBundle\EventListener\Security

services:
    netgen_admin_ui.event_listener.security:
        class: "%netgen_admin_ui.event_listener.security.class%"
        arguments:
            - "@request_stack"
            - "@ezpublish.api.repository"
            - "@ezpublish.config.resolver"
            - "@security.context"
        tags:
            - { name: kernel.event_subscriber }
