parameters:
    ngmore_admin_ui.templating.global_helper.class: Netgen\Bundle\MoreAdminUIBundle\Templating\GlobalHelper
    ngmore_admin_ui.templating.twig.extension.class: Netgen\Bundle\MoreAdminUIBundle\Templating\Twig\Extension\NetgenMoreAdminUIExtension
    ngmore_admin_ui.templating.converter.tag.class: Netgen\Bundle\MoreAdminUIBundle\Templating\Converter\TagConverter

services:
    ngmore_admin_ui.templating.global_helper:
        class: "%ngmore_admin_ui.templating.global_helper.class%"
        arguments:
            - "@ngmore_admin_ui.menu_plugin.registry"
            - "@request_stack"

    ngmore_admin_ui.templating.twig.extension:
        class: "%ngmore_admin_ui.templating.twig.extension.class%"
        arguments:
            - "@ezpublish_legacy.kernel"
            - "@ngmore_admin_ui.templating.global_helper"
        tags:
            - { name: twig.extension }
