parameters:
    ngmore_admin_ui.templating.twig.extension.class: Netgen\Bundle\MoreAdminUIBundle\Templating\Twig\Extension\NetgenMoreAdminUIExtension

services:
    ngmore_admin_ui.templating.twig.extension:
        class: %ngmore_admin_ui.templating.twig.extension.class%
        arguments:
            - @ezpublish_legacy.kernel
        tags:
            - { name: twig.extension }
