parameters:
    netgen_admin_ui.templating.global_helper.class: Netgen\Bundle\AdminUIBundle\Templating\GlobalHelper
    netgen_admin_ui.templating.twig.extension.class: Netgen\Bundle\AdminUIBundle\Templating\Twig\Extension\NetgenAdminUIExtension

services:
    netgen_admin_ui.templating.global_helper:
        class: "%netgen_admin_ui.templating.global_helper.class%"
        arguments:
            - "@netgen_admin_ui.menu_plugin.registry"
            - "@request_stack"

    netgen_admin_ui.templating.twig.extension:
        class: "%netgen_admin_ui.templating.twig.extension.class%"
        arguments:
            - "@ezpublish_legacy.kernel"
            - "@netgen_admin_ui.templating.global_helper"
        tags:
            - { name: twig.extension }
