services:
    netgen_admin_ui.controller.layouts:
        class: Netgen\Bundle\AdminUIBundle\Controller\LayoutsController
        public: true
        parent: netgen_admin_ui.controller.base
        arguments:
            - "@netgen_block_manager.layout.resolver"
            - "@netgen_block_manager.api.service.layout"
            - "@database_connection"
