services:
    netgen_admin_ui.controller.layouts:
        class: Netgen\Bundle\AdminUIBundle\Controller\LayoutsController
        public: true
        parent: netgen_admin_ui.controller.base
        arguments:
            - "@netgen_layouts.layout.resolver"
            - "@netgen_admin_ui.layouts.related_layouts_loader"
